---
apiVersion: v1
kind: Service
metadata:
   name: eks-service
   labels:
     app: kensta
spec:
  type: NodePort
  selector:
      app: kensta
  ports:
    - NodePort: 30163
      port: 8080
      targetPort: 8080    
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kensta
  labels:
    app: kensta
spec:
 selector:
    matchLabels:
      app: kensta
replicas: 3
template:
  metadata:
     labels:
       app: kensta
  spec:  
   conatiners:
    - name: kensta
      image: 56234/ensta
      imagePullPolicy: Always
      ports:
        - containerPort: 8080