---
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-service
  labels:
    name: myapp
spec:
  type: NodePort
  selector:
    name: myapp
  ports:
    - NodePort: 30163
      port: 8080
      targetPort: 8080    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata: # Dictionary
      labels: # Dictionary
        name: myapp
    spec:
      containers: # List
        - name: myapp
          image: 56234/ensta:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
